# Generated by Django 5.0.1 on 2024-03-30 07:36

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments_b',
            fields=[
                ('app_id', models.IntegerField(default=api.models.generate_unique_appointment_id, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.IntegerField(default=api.models.generate_unique_payment_id, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('upi', 'upi'), ('card', 'card')], default='upi', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('canceled', 'canceled')], default='complete', max_length=10)),
                ('paid_am', models.IntegerField()),
                ('pending_am', models.IntegerField(default=0)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.IntegerField(default=api.models.generate_unique_user_id, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_master_b',
            fields=[
                ('offer_id', models.IntegerField(default=api.models.generate_unique_offer_id, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('p_id', models.IntegerField(default=api.models.generate_unique_p_id, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointments_b_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.appointments_b')),
                ('date_of_book', models.DateField(default=django.utils.timezone.now)),
                ('date_of_appointment', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tot_duration', models.DurationField(default='00:00:00')),
                ('total_amm', models.IntegerField()),
                ('canceled', models.BooleanField(default=False)),
                ('cancellation_reasion', models.CharField(default=None, max_length=100, null=True)),
                ('app_status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('canceled', 'canceled')], max_length=20)),
                ('app_mode', models.CharField(choices=[('salon', 'salon'), ('home', 'home')], default='salon', max_length=20)),
            ],
            bases=('api.appointments_b',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('pay_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.payment')),
                ('card_no', models.IntegerField()),
                ('hold_name', models.CharField(max_length=40)),
                ('exp_date', models.DateField()),
                ('cvv_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('pay_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.payment')),
                ('upi_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('cash_id', models.IntegerField(default=api.models.generate_unique_cash_id, primary_key=True, serialize=False)),
                ('amm', models.IntegerField()),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='p_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profiles'),
        ),
        migrations.CreateModel(
            name='S_Admin',
            fields=[
                ('admin_id', models.IntegerField(default=api.models.generate_unique_admin_id, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('p_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('salon_id', models.IntegerField(default=api.models.generate_unique_salon_id, primary_key=True, serialize=False, unique=True)),
                ('salon_password', models.CharField(max_length=20)),
                ('salon_name', models.CharField(max_length=30)),
                ('cust_gender', models.CharField(choices=[('Both', 'Both'), ('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.s_admin')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon'),
        ),
        migrations.CreateModel(
            name='Salon_media',
            fields=[
                ('img_id', models.IntegerField(default=api.models.generate_unique_img_id, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/')),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(default=api.models.generate_unique_schedule_id, primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(max_length=50)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('upcoming_holiday', models.DateField(default=None, null=True)),
                ('salon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Services_master',
            fields=[
                ('service_id', models.IntegerField(default=api.models.generate_unique_service_id, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('hair', 'hair'), ('beard', 'beard'), ('massage', 'massage'), ('facials', 'facials')], default='hair', max_length=50)),
                ('typeofservice', models.CharField(max_length=100)),
                ('img', models.ImageField(default='default_image.jpg', upload_to='images/')),
                ('duration', models.TimeField()),
                ('charge', models.IntegerField()),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.states')),
            ],
        ),
        migrations.CreateModel(
            name='Stylists',
            fields=[
                ('sty_id', models.IntegerField(default=api.models.generate_unique_stylist_id, primary_key=True, serialize=False, unique=True)),
                ('expertice', models.CharField(max_length=40)),
                ('p_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAddress',
            fields=[
                ('user_address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cities')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.states')),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersaddress'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usersaddress'),
        ),
        migrations.AddField(
            model_name='payment',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointments'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.CreateModel(
            name='Offer_master',
            fields=[
                ('offer_master_b_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.offer_master_b')),
                ('offer_name', models.CharField(max_length=30)),
                ('offer_type', models.CharField(max_length=20)),
                ('offer_date', models.DateField()),
                ('offer_end', models.DateField()),
                ('off_amm', models.IntegerField()),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services_master')),
            ],
            bases=('api.offer_master_b',),
        ),
        migrations.CreateModel(
            name='Appointed_stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amm', models.IntegerField()),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services_master')),
                ('sty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stylists')),
            ],
            options={
                'unique_together': {('sty_id', 'salon_id', 'service_id')},
            },
        ),
        migrations.CreateModel(
            name='Stylist_appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amm', models.IntegerField()),
                ('sty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stylists')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointments')),
            ],
            options={
                'unique_together': {('sty_id', 'app_id')},
            },
        ),
        migrations.CreateModel(
            name='Provided_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services_master')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointments')),
                ('offer_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offer_master')),
            ],
            options={
                'unique_together': {('app_id', 'service_id')},
            },
        ),
    ]
