# Generated by Django 5.0.1 on 2024-04-12 17:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.IntegerField(default=api.models.generate_unique_city_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='state_id',
            field=models.IntegerField(default=api.models.generate_unique_state_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersaddress',
            name='user_address_id',
            field=models.IntegerField(default=api.models.generate_unique_address_id, primary_key=True, serialize=False),
        ),
    ]
