# Generated by Django 5.0.1 on 2024-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cities_city_id_alter_states_state_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='address',
            new_name='user_address_id',
        ),
    ]
