# Generated by Django 5.0.1 on 2024-04-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_address_profiles_user_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='address',
            new_name='salon_address_id',
        ),
    ]
