from django.urls import path
# from .views import main
from django.conf.urls.static import static
from django.conf import settings
from .views import generate_unique_p_id_view,generate_unique_user_id_view,generate_unique_admin_id_view,generate_unique_salon_id_view,generate_unique_schedule_id_view,generate_unique_appointments_id_view,generate_unique_service_id_view,generate_unique_address_id_view,generate_unique_img_id_view
from .views import (
                    ProfileListCreateView, CustomerListCreateView, AdminListCreateView,
                     SalonListCreateView,ScheduleListCreateView,UpiListView,
                     CardListView,CashListView,PaymentListView,OfferMasterListView,
                     AppointmentsListView,ServicesMasterListView,StylistsListCreateView,
                     AppointedStylistListView,ProvidedServicesListView,
                     StylistAppointmentsListView,CustomerUpdateView,CompletedAppointmentsListView,
                     CenceledAppointmentsListView,PendingAppointmentsListView,LoginApiView,
                     SalonRetrieveView,SalonMediaListView,SalonMediaImgView,ScheduleListRetrieveView,
                     ServiceMasterListRetrieveView,AppointmentListRetrieveView,CheckAppointmentAvailability,
                     CustomerListRetrieveView,AdminListRetrieveView,SalonRetrieveByAdminIdView,
                     AppointmentsUpdateView,ServiceMasterUpdateView,StatesListCreateView,CitiesListCreateView,
                     UserAddressListCreateView,SalonAddressListCreateView,UseraddresssearchView,CitysearchView,
                     SalonaddresssearchView,SalonDataRetrieveAsGenderView,SalonDataRetrieveAsSearchView,
                     StatesNameSearchByIdView,CitysearchByStateView,SalonFilterByStatesIdView,
                     SalonFilterByCityIdView,ServiceMasterCategorysListCreateview,
                     ServiceMasterCategorysTypesListCreateview,CategorySearchByIdView,CategoryTypeSearchByIdView,
                     ServicesMasterDeleteView,ProfileListByPIdCreateView,SalonUpdateView,SalonAddressUpdateView,
                     ProfileUpdateView,UserAddressUpdateView,SalonImageUpdateView,CategoryTypeSearchcategoryByIdView,
                     ForgotPasswordCustomerView,SalonMediaImageUploadListView,)
from rest_framework_simplejwt import views as jwt_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
# from .views import MyTokkenObtainPairView

urlpatterns = [
    # path('', main),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path('user-login/', LoginApiView.as_view(), name='user_login'),
    path('forgotpassword/', ForgotPasswordCustomerView.as_view(),name='forgotpassword'),
    path('state/', StatesListCreateView.as_view(), name='state-list-create'),
    path('state/<str:state_id>/', StatesNameSearchByIdView.as_view(), name='state-name-by-id-create'),
    path('city/', CitiesListCreateView.as_view(), name='city-list-create'),
    path('city/<str:city_id>/', CitysearchView.as_view(), name='city-search-list-create'),
    path('city/bystate/<str:state_id>/', CitysearchByStateView.as_view(), name='city-search-list-create'),
    path('servicemastercategory/', ServiceMasterCategorysListCreateview.as_view(), name='service-master-category-list-create'),
    path('servicemastercategory/<str:categorys_id>/', CategorySearchByIdView.as_view(), name='category-by-id-create'),
    path('servicemastercategorytypes/', ServiceMasterCategorysTypesListCreateview.as_view(), name='service-master-category-types-list-create'),
    path('servicemastercategorytypesbycat/<str:categorys_id>/', CategoryTypeSearchcategoryByIdView.as_view(), name='service-master-category-types-list-create'),
    path('servicemastercategorytypes/<str:category_types_id>/', CategorySearchByIdView.as_view(), name='category-types-list-create'),
    path('useraddress/', UserAddressListCreateView.as_view(), name='useraddress-list-create'),
    path('useraddressupdate/<int:user_address_id>/', UserAddressUpdateView.as_view(), name='useraddress-update-list-create'),
    path('salonaddress/', SalonAddressListCreateView.as_view(), name='salonaddress-list-create'),
    path('salonaddressupdate/<int:salon_address_id>/', SalonAddressUpdateView.as_view(), name='salonaddress-update-list-create'),
    path('useraddress/<str:user_address_id>/', UseraddresssearchView.as_view(), name='useraddress-search-list-create'),
    path('salonaddress/<str:salon_address_id>/', SalonaddresssearchView.as_view(), name='salonaddress-search-list-create'),
    path('generate-unique-p-id/', generate_unique_p_id_view, name='generate-unique-p-id'),
    path('generate-unique-salon-id/', generate_unique_salon_id_view, name='generate-unique-salon-id'),
    path('generate-unique-user-id/', generate_unique_user_id_view, name='generate-unique-user-id'),
    path('generate-unique-admin-id/', generate_unique_admin_id_view, name='generate-unique-admin-id'),
    path('generate-unique-salon-id/', generate_unique_salon_id_view, name='generate-unique-salon-id'),
    path('generate-unique-schedule-id/', generate_unique_schedule_id_view, name='generate-unique-schedule-id'),
    path('generate-unique-appointment-id/', generate_unique_appointments_id_view, name='generate-unique-appointment-id'),
    path('generate-unique-service-id/', generate_unique_service_id_view, name='generate-unique-service-id'),
    path('generate-unique-address-id/', generate_unique_address_id_view, name='generate-unique-address-id'),
    path('generate-unique-img-id/', generate_unique_img_id_view, name='generate-unique-img-id'),
    path('profiles/', ProfileListCreateView.as_view(), name='profile-list-create'),
    path('profilesupdate/<int:p_id>', ProfileUpdateView.as_view(), name='profile-update-list-create'),
    path('profiles/<str:p_id>', ProfileListByPIdCreateView.as_view(), name='profile-list-byid-create'),
    path('customers/', CustomerListCreateView.as_view(), name='customer-list-create'),
    path('customers/<str:user_id>/', CustomerListRetrieveView.as_view(), name='customer-value-get'),
    path('customers-u/<int:pk>/', CustomerUpdateView.as_view(), name='customer-u-list-create'),
    # path('cust-auth/', LoginAuthontication.as_view(), name='customer-authentication'),
    path('s-admin/', AdminListCreateView.as_view(), name='admin-list-create'),
    path('s-admin/r-salon/stylists/', StylistsListCreateView.as_view(), name='stylists-list-create'),
    path('s-admin/r-salon/', SalonListCreateView.as_view(), name='salon-list-create'),
    path('s-admin/r-salonupdate/<int:salon_id>', SalonUpdateView.as_view(), name='salon-update-list-create'),
    path('s-admin/r-salon/salon-media/', SalonMediaListView.as_view(), name='salon-media-list'),
    path('s-admin/r-salon/salon-media-imgchange/<str:salon_id>/', SalonImageUpdateView.as_view(), name='salon-mediaimg-change-list'),
    path('s-admin/r-salon/salon-media-imgpost/<str:salon_id>/', SalonMediaImageUploadListView.as_view(), name='salon-mediaimg-change-list'),
    path('s-admin/r-salon/salon-media/<str:salon_id>/', SalonMediaImgView.as_view(), name='salon-media-list'),
    path('s-admin/r-salon/provided_services/', ProvidedServicesListView.as_view(), name='provided_services-list-create'),
    path('s-admin/r-salon/offer_master/', OfferMasterListView.as_view(), name='offer_master-list-create'),
    path('s-admin/r-salon/appointed_stylist/', AppointedStylistListView.as_view(), name='appointed_stylist-list-create'),
    path('s-admin/r-salon/stylist_appointments/', StylistAppointmentsListView.as_view(), name='stylist_appointed-list-create'),
    path('s-admin/r-salon/schedule/', ScheduleListCreateView.as_view(), name='schedule-create'),
    path('s-admin/r-salon/service_master/', ServicesMasterListView.as_view(), name='service_master-list-create'),
    path('s-admin/r-salon/service_master/delete/<int:pk>', ServicesMasterDeleteView.as_view(), name='service_master-delete-list-create'),
    path('s-admin/r-salon/service_master/<str:salon_id>/', ServiceMasterListRetrieveView.as_view(), name='service_master-selected-data'),
    path('s-admin/r-salon/service_master-u/<int:pk>/', ServiceMasterUpdateView.as_view(), name='service_master-data-update'),
    path('s-admin/r-salon/schedule/<str:salon_id>/', ScheduleListRetrieveView.as_view(), name='schedule-details'),
    path('s-admin/r-salon/byadmin/<str:admin_id>/', SalonRetrieveByAdminIdView.as_view(), name='salon-detail_by_admin_id'),
    path('s-admin/r-salon/<str:salon_id>/', SalonRetrieveView.as_view(), name='salon-detail'),
    path('s-admin/r-salon/bystate-id/<str:state_id>/', SalonFilterByStatesIdView.as_view(), name='salon-filterby-state-id-detail'),
    path('s-admin/r-salon/bycity-id/<str:city_id>/', SalonFilterByCityIdView.as_view(), name='salon-filterby-city-id-detail'),
    path('s-admin/r-salon/bygender/<str:cust_gender>/', SalonDataRetrieveAsGenderView.as_view(), name='salon-detail'),
    path('s-admin/r-salon/bysalonname/<str:salon_name>/', SalonDataRetrieveAsSearchView.as_view(), name='salon-detail'),
    path('s-admin/<str:admin_id>', AdminListRetrieveView.as_view(), name='admin-value-get'),
    path('appointments/completed/<str:salon_id>/', CompletedAppointmentsListView.as_view(), name='completed-appointments-list-create'),
    path('appointments/canceled/<str:salon_id>/', CenceledAppointmentsListView.as_view(), name='cenceled-appointments-list-create'),
    path('appointments/pending/<str:salon_id>/', PendingAppointmentsListView.as_view(), name='pending-appointments-list-create'),
    path('appointments-u/<int:pk>/', AppointmentsUpdateView.as_view(), name='pending-appointments-list-create'),
    path('appointments/payments/', PaymentListView.as_view(), name='payments-list-create'),
    path('appointments/payments/cash/', CashListView.as_view(), name='cash-list-create'),
    path('appointments/payments/upi/', UpiListView.as_view(), name='upi-list-create'),
    path('appointments/payments/card/', CardListView.as_view(), name='card-list-create'),
    path('appointments/', AppointmentsListView.as_view(), name='appointments-list-create'),
    path('ch-appointments/', CheckAppointmentAvailability.as_view(), name='check_appointment_availability'),
    path('appointments/<str:salon_id>/', AppointmentListRetrieveView.as_view(), name='appointments-details-get'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)